TestAppAspCore/Areas/Market/ViewModels/ShowBooksViewModel.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using TestAppAspCore.ViewModels;

namespace TestAppAspCore.Areas.Market.ViewModels
{
    public class ShowBooksViewModel : IndexBookViewModel
    {
        public string Genre { get; set; } = string.Empty;
        public string ActionName { get; set; }
    }
}

TestAppAspCore/ViewModels/ShowOrderViewModel.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace TestAppAspCore.ViewModels
{
    public class ShowOrderViewModel
    {
        public int OrderID { get; set; }
        public string UserName { get; set; }
        public DateTime DateReturn { get; set; }
    }
}

TestAppAspCore/ViewModels/ShowUserViewModel.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using TestAppAspCore.Models;

namespace TestAppAspCore.ViewModels
{
    public class ShowUserViewModel
    {
        public string RoleName { get; set; }
        public User User { get; set; }
    }
}

TestAppAspCore/Areas/Market/Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using TestAppAspCore.Areas.Market.ViewModels;
using TestAppAspCore.DBRepositories;
using TestAppAspCore.ModelHelpers;
using TestAppAspCore.Models;
using TestAppAspCore.ViewModels;

namespace TestAppAspCore.Areas.Market.Controllers
{
    [Area("Market")]
    [Authorize(Roles = RolesHelper.USER_ROLE)]
    public class HomeController : Controller
    {
        private readonly int COUNT_ELEMS_ON_PAGE;

        private readonly IBooksRepository _booksRepository;
        private readonly IGenresRepository _genresRepository;

        public HomeController(IBooksRepository booksRepository, IGenresRepository genresRepository, int countElemOnPage = 8)
        {
            _genresRepository = genresRepository;
            _booksRepository = booksRepository;
            COUNT_ELEMS_ON_PAGE = countElemOnPage;
        }

        [HttpGet]
        public async Task<IActionResult> ShowBooks(string searchExpr, int? page = 1)
        {
            IEnumerable<Book> books = new List<Book>();
            ShowBooksViewModel indexViewModel;
            if (string.IsNullOrEmpty(searchExpr))
            {
                books = await _booksRepository.GetAllBooks();
            }
            else
            {
                books = await _booksRepository.GetBooksByFilter(searchExpr, _genresRepository.GetAllGenres().ToList());
            }
            indexViewModel = new ShowBooksViewModel
            {
                Books = _booksRepository.PartBooksForPage(books, page.Value, COUNT_ELEMS_ON_PAGE)
                .Select(book => BookConverter.ConvertModelToViewModel(book)).ToList(),
                PageViewModel = new PageViewModel(books.Count(), page.Value, COUNT_ELEMS_ON_PAGE),
                SearchExpr = String.IsNullOrEmpty(searchExpr) ? string.Empty : searchExpr,
                ActionName = nameof(this.ShowBooks)
            };
            return View(indexViewModel);
        }

        [HttpGet]
        public async Task<IActionResult> ShowBooksByGenre(string genre, string searchExpr, int? page = 1)
        {
            IEnumerable<Book> books = new List<Book>();
            ShowBooksViewModel indexViewModel;

            if (string.IsNullOrEmpty(searchExpr))
            {
                books = await _booksRepository.GetBooksByGenre(genre);
            }
            else
            {
                books = await _booksRepository.GetBooksByFilter(searchExpr, genre);
            }

            indexViewModel = new ShowBooksViewModel
            {
                Books = _booksRepository.PartBooksForPage(books, page.Value, COUNT_ELEMS_ON_PAGE)
                                .Select(book => BookConverter.ConvertModelToViewModel(book)).ToList(),
                PageViewModel = new PageViewModel(books.Count(), page.Value, COUNT_ELEMS_ON_PAGE),
                Genre = genre,
                SearchExpr = String.IsNullOrEmpty(searchExpr) ? string.Empty : searchExpr,
                ActionName = nameof(this.ShowBooksByGenre)
            };
            return View(nameof(ShowBooks),indexViewModel);
        }

        [HttpGet]
        public async Task<IActionResult> ShowOrders([FromServices] IOrdersRepository ordersRepository, 
                                                    [FromServices] UserManager<User> userManager)
        {
            var userID = (await userManager.FindByNameAsync(User.Identity.Name)).Id;
            return View(ordersRepository.GetOrdersForUser(userID));
        }

        [HttpGet]
        public async Task<IActionResult> ShowStore([FromServices] IBookOrderRepository boRepository,
                                            [FromServices] UserManager<User> userManager)
        {
            var userID = (await userManager.FindByNameAsync(User.Identity.Name)).Id;
            return View(new StoreBooksViewModel
            {
                StoreBooks = boRepository.GetBooksForUser(userID, null).ToList(),
                NotConfirmedBooks = boRepository.GetBooksForUser(userID, false).ToList()
            });            
        }
    }
}

TestAppAspCore/Controllers/BookController.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using System;
using TestAppAspCore.DBRepositories;
using TestAppAspCore.ModelHelpers;
using TestAppAspCore.Models;
using TestAppAspCore.ViewModels;
using System.Linq;
using Microsoft.AspNetCore.Authorization;

namespace TestAppAspCore.Controllers
{
    [Authorize(Roles = RolesHelper.ADMIN_ROLE + "," + RolesHelper.STOREKEEPER_ROLE)]
    public class BookController : Controller
    {
        private readonly IBooksRepository _booksRepository;
        private readonly IGenresRepository _genresRepository;

        public BookController(IBooksRepository booksRepository, IGenresRepository genresRepository)
        {
            _booksRepository = booksRepository;
            _genresRepository = genresRepository;
        }

        // GET: Book/Create
        [HttpGet]
        public ActionResult Create()
        {
            return View(new ActionBooksPagesViewModel
            {
                Book = null,
                Genres = new SelectList(_genresRepository.GetAllGenres(), nameof(Genre.Id), nameof(Genre.Title)),
                PrevPageUrl = HttpContext.Request.Headers["Referer"].ToString()
            });
        }

        // POST: Book/Create
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create(BookViewModel book, string prevPageUrl)
        {
            if (ModelState.IsValid)
            {
                _booksRepository.AddElem(BookConverter.ConvertViewModelToModel(book));
                TempData["message"] = $"Книга \"{book.Title}\" успешно добавлена";
                return RedirectToAction(nameof(HomeController.Index), nameof(HomeController).Replace("Controller", ""));
            }
            else
            {
                return View(new ActionBooksPagesViewModel
                {
                    Book = book,
                    Genres = new SelectList(_genresRepository.GetAllGenres(), nameof(Genre.Id), nameof(Genre.Title)),
                    PrevPageUrl = prevPageUrl
                });
            }
        }

        // GET: Book/Edit/{id}
        [HttpGet]
        public ActionResult Edit(int id)
        {
            var book = BookConverter.ConvertModelToViewModel(_booksRepository.GetElem(id));

            return View(new ActionBooksPagesViewModel
            {
                Book = book,
                Genres = new SelectList(_genresRepository.GetAllGenres(), nameof(Genre.Id), nameof(Genre.Title),
                                        _genresRepository.GetAllGenres().FirstOrDefault(g => g.Id == book.GenreId)),
                PrevPageUrl = HttpContext.Request.Headers["Referer"].ToString()
            }); 
        }

        // POST: Book/Edit/
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit(BookViewModel book, string prevPageUrl)
        {
            if (book.Id <= 0)
                throw new ArgumentException("Book ID is empty or <= 0");
            if (ModelState.IsValid)
            {
                _booksRepository.EditElem(BookConverter.ConvertViewModelToModel(book));
                TempData["message"] = $"Книга \"{book.Title}\" успешно изменена";
                return RedirectToAction(nameof(HomeController.Index), nameof(HomeController).Replace("Controller", ""));
            }
            else
            {
                return View(new ActionBooksPagesViewModel
                {
                    Book = book,
                    Genres = new SelectList(_genresRepository.GetAllGenres(), nameof(Genre.Id), nameof(Genre.Title),
                                        _genresRepository.GetAllGenres().FirstOrDefault(g => g.Id == book.GenreId)),
                    PrevPageUrl = prevPageUrl
                });
            }
        }

        // GET: Book/Show/{id}
        [HttpGet]
        public ActionResult Show(int id)
        {
            var book = BookConverter.ConvertModelToViewModel(_booksRepository.GetElem(id));

            return View(book);
        }

        // GET: Book/Delete/{id}
        [HttpGet]
        public ActionResult Delete(int id)
        {
            var book = BookConverter.ConvertModelToViewModel(_booksRepository.GetElem(id));

            return View(new ActionBooksPagesViewModel
            {
                Book = book,
                Genres = new SelectList(_genresRepository.GetAllGenres(), nameof(Genre.Id), nameof(Genre.Title),
                                        _genresRepository.GetAllGenres().FirstOrDefault(g => g.Id == book.GenreId)),
                PrevPageUrl = HttpContext.Request.Headers["Referer"].ToString()
            });
        }

        // POST: Book/Delete/
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Delete(BookViewModel book, string prevPageUrl)
        {
            if (book.Id <= 0)
                throw new ArgumentException("Book ID is empty or <= 0");
            if (ModelState.IsValid)
            {
                _booksRepository.DeleteElem(BookConverter.ConvertViewModelToModel(book));
                TempData["message"] = $"Книга \"{book.Title}\" успешно удалена";
                return RedirectToAction(nameof(HomeController.Index), nameof(HomeController).Replace("Controller", ""));
            }
            else
            {
                return View(new ActionBooksPagesViewModel
                {
                    Book = book,
                    Genres = new SelectList(_genresRepository.GetAllGenres(), nameof(Genre.Id), nameof(Genre.Title),
                                        _genresRepository.GetAllGenres().FirstOrDefault(g => g.Id == book.GenreId)),
                    PrevPageUrl = prevPageUrl
                });
            }
        }
    }
}

TestAppAspCore/Controllers/GenreController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using TestAppAspCore.DBRepositories;
using TestAppAspCore.Models;
using TestAppAspCore.ViewModels;

namespace TestAppAspCore.Controllers
{
    [Authorize(Roles = RolesHelper.ADMIN_ROLE + "," + RolesHelper.STOREKEEPER_ROLE)]
    public class GenreController : Controller
    {
        private readonly IGenresRepository _genresRepository;

        public GenreController(IGenresRepository genresRepository)
        {
            _genresRepository = genresRepository;
        }

        // GET: Genre/Create
        [HttpGet]
        public ActionResult Create()
        {
            return View();
        }

        // POST: Genre/Create
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create(Genre genre)
        {
            if (ModelState.IsValid)
            {
                _genresRepository.AddElem(new Genre { Title = genre.Title });
                TempData["message"] = $"Жанр \"{genre.Title}\" успешно добавлен";
                return RedirectToAction(nameof(HomeController.ShowGenres), nameof(HomeController).Replace("Controller", ""));
            }
            else
            {
                return View(genre);
            }
        }

        // GET: Genre/Edit/{id}
        [HttpGet]
        public ActionResult Edit(int id)
        {
            var genre = _genresRepository.GetElem(id);

            return View(genre);
        }

        // POST: Genre/Edit/
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit(Genre genre)
        {
            if (genre.Id <= 0)
                throw new ArgumentException("Genre ID is empty or <= 0");
            if (ModelState.IsValid)
            {
                _genresRepository.EditElem(genre);
                TempData["message"] = $"Жанр \"{genre.Title}\" успешно изменен";
                return RedirectToAction(nameof(HomeController.ShowGenres), nameof(HomeController).Replace("Controller", ""));
            }
            else
            {
                return View(genre);
            }
        }

        // GET: Genre/Delete/{id}
        [HttpGet]
        public ActionResult Delete(int id)
        {
            var genre = _genresRepository.GetElem(id);

            return View(genre);
        }

        // POST: Genre/Delete/
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Delete(Genre genre)
        {
            if (genre.Id <= 0)
                throw new ArgumentException("Genre ID is empty or <= 0");
            if (ModelState.IsValid)
            {
                _genresRepository.DeleteElem(genre);
                TempData["message"] = $"Жанр \"{genre.Title}\" успешно удален";
                return RedirectToAction(nameof(HomeController.ShowGenres), nameof(HomeController).Replace("Controller", ""));
            }
            else
            {
                return View(genre);
            }
        }
    }
}

TestAppAspCore/Controllers/OrderController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using TestAppAspCore.DBRepositories;
using TestAppAspCore.Models;
using TestAppAspCore.ViewModels;

namespace TestAppAspCore.Controllers
{
    [Authorize(Roles = RolesHelper.ADMIN_ROLE + "," + RolesHelper.BOOKKEEPER_ROLE)]
    public class OrderController : AbstractOrderController
    {
        public OrderController(IOrdersRepository ordersRepository, IBookOrderRepository bookOrderRepository, IBooksRepository booksRepository) :
            base(ordersRepository, bookOrderRepository, booksRepository)
        {
        }

        [ValidateAntiForgeryToken]
        [HttpPost]
        public IActionResult ConfirmOrder(int orderID)
        {
            _ordersRepository.ConfirmOrder(orderID);
            return Json(new { ID = orderID, message = $"Заказ {orderID} подтвержден!" });
        }

        [ValidateAntiForgeryToken]
        [HttpPost]
        public IActionResult CancelOrder(int orderID)
        {
            _ordersRepository.CancelOrder(orderID);
            //возвращаем книги на склад
            _ordersRepository.GetOrder(orderID)
                .BookOrders.ToList().ForEach((BookOrder bo) =>
                {
                    var book = _booksRepository.GetElem(bo.BookId);
                    _booksRepository.IncCountBooks(book, bo.CountOfBook);
                });
            return Json(new { ID = orderID, message = $"Заказ {orderID} отменен!" });
        }
    }
}

TestAppAspCore/Controllers/StoreController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using TestAppAspCore.DBRepositories;
using TestAppAspCore.Models;

namespace TestAppAspCore.Controllers
{
    [Authorize(Roles = RolesHelper.ADMIN_ROLE + "," + RolesHelper.BOOKKEEPER_ROLE)]
    public class StoreController : Controller
    {
        private readonly IBookOrderRepository _boRepository;

        public StoreController(IBookOrderRepository bookOrderRepository)
        {
            _boRepository = bookOrderRepository;
        }

        public IActionResult ConfirmReturnBook(int bookId, int countReturnBooks, [FromServices] IBooksRepository booksRepository)
        {
            _boRepository.ConfirmBook(bookId);
            Book book = booksRepository.GetElem(bookId);
            booksRepository.IncCountBooks(book, countReturnBooks);

            return Json(new { id = bookId, message = "Книга успешно возвращена в библиотеку!" });
        }

        public IActionResult CancelReturnBook(int bookId)
        {
            _boRepository.CancelBook(bookId);
            return Json(new { id = bookId, message = "Книга возвращена пользователю!" });
        }
    }
}

TestAppAspCore/Views/Home/ErrorStatusCode.cshtml
@{
    ViewData["Title"] = "HTTP ошибка";
    Layout = "~/Views/Shared/_Layout.cshtml";
}
<br />
<h2>Ошибка!</h2>
<pre>

Возникла ошибка с кодом @ViewBag.ErrorCode.
Подробную информацию по данной ошибке можно найти по <a href="https://ru.wikipedia.org/wiki/%D0%A1%D0%BF%D0%B8%D1%81%D0%BE%D0%BA_%D0%BA%D0%BE%D0%B4%D0%BE%D0%B2_%D1%81%D0%BE%D1%81%D1%82%D0%BE%D1%8F%D0%BD%D0%B8%D1%8F_HTTP#@ViewBag.ErrorCode">ссылке</a>.

Приносим извинения за неудобства!

Пожалуйста, обратитесь в службу поддержки для решения возникшей проблемы или напишите о проблеме на почту <a href="mailto:m.vlasov@qpdev.ru">m.vlasov@qpdev.ru</a>

</pre>

TestAppAspCore/Views/Home/Index.cshtml
@model IndexBookViewModel
@{
    ViewData["Title"] = "Список книг";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<div class="row body-container">
    @Html.Partial("_MenuPartialView")
    <div class="container body-content col-sm-9 col-md-10 offset-sm-3 offset-md-2 ">
        <br />
        <form asp-controller="Home" asp-action="Index" asp-route-page="1" method="get">
            <h2>Фильтр</h2>
            <div class="form-inline form-group">
                <label for="searchExpr" class="control-label"></label>
                <input name="searchExpr" id="tbSearchExpr" type="text" class="form-control searchTextbox" value="@Model.SearchExpr" />
                <button id="btnSearch" type="submit" class="btn btn-default"><i class="fas fa-search"></i></button>
            </div>
        </form>
        @if (TempData["message"] != null)
        {
            <div id="alert-closing" class="alert alert-success">@TempData["message"]</div>
        }
        <h2>Список книг</h2>
        <table class="table-condensed">
            <tr>
                <th class="text-center">Название</th>
                <th class="text-center">Автор</th>
                <th class="text-center">Жанр</th>
                <th class="text-center">Дата создания</th>
                <th class="text-center">Количество</th>
                <th class="text-center">Действия</th>
            </tr>
            @foreach (var book in Model.Books)
            {
                <tr>
                    <td>@book.Title</td>
                    <td>@book.Author</td>
                    <td>@book.GenreTitle</td>
                    <td>@book.DateCreating.Year</td>
                    <td>@book.Count</td>
                    <td>
                        <a asp-controller="Book" asp-action="Edit" asp-route-id="@book.Id" class="btn btn-info">Изменить</a>
                        <a asp-controller="Book" asp-action="Delete" asp-route-id="@book.Id" class="btn btn-danger">Удалить</a>
                    </td>
                </tr>
            }
        </table>
        <br />
        <page-link page-controller="Home" page-action="Index" page-model="@Model.PageViewModel" page-url-searchExpr="@Model.SearchExpr"></page-link>
        <a asp-controller="Book" asp-action="Create" class="btn btn-success">Создание книги</a>
        <br /><br />
    </div>
</div>   

TestAppAspCore/Views/Home/ShowBooks.cshtml
@model TestAppAspCore.ViewModels.IndexBookViewModel
@{
    ViewData["Title"] = "Список книг";
    Layout = "~/Views/Shared/_Layout.cshtml";
}
<div>
    <form asp-controller="Home" asp-action="ShowBooks" asp-route-page="1" method="get">
        <h2>Фильтр</h2>
        <div class="form-inline form-group">
            <label for="searchExpr" class="control-label"></label>
            <input name="searchExpr" id="tbSearchExpr" type="text" class="form-control searchTextbox" value="@Model.PageViewModel.SearchExpr"/>
            <button id="btnSearch" type="submit" class="btn btn-default"><i class="fas fa-search"></i></button>
        </div>
    </form>

    <h2>Список книг</h2>
    <table class="table-condensed">
        <tr>
            <td>Название</td>
            <td>Автор</td>
            <td>Жанр</td>
            <td>Дата создания</td>
            <td>Действия</td>
        </tr>
        @foreach (var book in Model.Books)
        {
            <tr>
                <td>@book.Title</td>
                <td>@book.Author</td>
                <td>@book.GenreTitle</td>
                <td>@book.DateCreating.Year</td>
                <td>
                    <a asp-controller="Book" asp-action="Edit" asp-route-id="@book.Id" class="btn btn-info" style="padding-right:10px;">Изменить</a>
                    <a asp-controller="Book" asp-action="Delete" asp-route-id="@book.Id" class="btn btn-danger">Удалить</a>
                </td>
            </tr>
        }
    </table>
    <br />
    <page-link page-controller="Home" page-action="ShowBooks" page-model="@Model.PageViewModel"></page-link>
    <button id="createBook" class="btn btn-success">Создание книги</button>

</div>
@section Footer {
    <script src="~/js/Basic.js" asp-append-version="true"></script>
}

TestAppAspCore/Views/Home/ShowGenres.cshtml
@model IEnumerable<TestAppAspCore.Models.Genre>
@{
    ViewData["Title"] = "Список жанров";
    Layout = "~/Views/Shared/_Layout.cshtml";
}
<div class="row body-container">
    @Html.Partial("_MenuPartialView")
    <div class="container body-content col-10 col-md-10 col-sm-9 offset-sm-3 offset-md-2">
        <br />
        @if (TempData["message"] != null)
        {
            <div id="alert-closing" class="alert alert-success">@TempData["message"]</div>
        }
        <h2>Список жанров</h2>
        <table class="table-condensed">
            <tr>
                <th class="text-center">Название</th>
                <th class="text-center">Книги</th>
                <th></th>
                <th></th>
            </tr>
            @foreach (var genre in Model)
        {
            <tr>
                <td>@genre.Title</td>
                <td>
                    @foreach (var book in genre.Books)
                {
                    <a asp-controller="Book" asp-action="Show" asp-route-id="@book.Id"><p>@book.Title</p></a>
            }
                </td>
                <td><a asp-controller="Genre" asp-action="Edit" asp-route-id="@genre.Id" class="btn btn-info">Изменить</a></td>
                <td><a asp-controller="Genre" asp-action="Delete" asp-route-id="@genre.Id" class="btn btn-danger">Удалить</a></td>
            </tr>
    }
        </table>
        <br />
        <a asp-controller="Genre" asp-action="Create" class="btn btn-success" role="button" aria-pressed="true">Создать жанр</a>
        <br /><br /><br /><br />
    </div>
</div>
@section Footer {
    <script src="~/js/Basic.js" asp-append-version="true"></script>
}

TestAppAspCore/Views/Home/ShowOrders.cshtml
@model IEnumerable<ShowOrderViewModel>
@{
    ViewData["Title"] = "Список необработанных заказов";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<div class="container">
    <div class="row">
        <div class="offset-2 col-7">
            <br />
            <h2>Необработанные заказы</h2>
            <br />
            @if (TempData["message"] != null)
            {
                <div id="alert-closing" class="alert alert-success">@TempData["message"]</div>
            }
            <div id="messageBox"></div>

            <table class="table table-striped">
                <thead>
                    <tr>
                        <th>ID заказа</th>
                        <th>Пользователь</th>
                        <th>Дата возврата</th>
                        <th class="text-center" colspan="3">Действия</th>
                    </tr>
                </thead>
                <tbody>
                    @foreach (var elem in Model)
                    {
                        <tr id="@elem.OrderID">
                            <td><a class="btn btn-link" asp-controller="Order" asp-action="ShowOrder" asp-route-orderID="@elem.OrderID">@elem.OrderID</a></td>
                            <td>@elem.UserName</td>
                            <td>@elem.DateReturn.ToShortDateString()</td>
                            <td class="text-center">
                                <a class="btn text-light btn-warning" asp-controller="Order" asp-action="EditOrder" asp-route-orderID="@elem.OrderID">Изменить</a>
                            </td>
                            <td>
                                <form class="d-inline-block" asp-action="ConfirmOrder" asp-controller="Order"
                                      data-ajax="true" data-ajax-method="POST"
                                      data-ajax-success="onSuccessConfirmOrder"
                                      data-ajax-failure="onFailedConfirmOrder">
                                    <input type="hidden" name="orderID" value="@elem.OrderID" />
                                    <button type="submit" class="btn btn-success ">Принять</button>
                                </form>
                            </td>
                            <td>
                                <form class="d-inline-block" asp-action="CancelOrder" asp-controller="Order"
                                      data-ajax="true" data-ajax-method="POST"
                                      data-ajax-success="onSuccessCancelOrder"
                                      data-ajax-failure="onFailedCancelOrder">
                                    <input type="hidden" name="orderID" value="@elem.OrderID" />
                                    <button type="submit" class="btn btn-danger ">Отклонить</button>
                                </form>
                            </td>
                        </tr>
                    }
                </tbody>
            </table>
        </div>
    </div>
</div>

@section Footer {
    <script src="~/lib/jquery-ajax-unobtrusive/jquery.unobtrusive-ajax.min.js"></script>
    <script src="~/js/BookKeeperOrderAJAX.js"></script>
}

TestAppAspCore/Views/Home/ShowReturnedBooks.cshtml
@model List<Book>
@{
    ViewData["Title"] = "Возвращенные книги";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<div class="container">
    <div class="row">
        <div class="offset-2 col-7">
            <br />
            <h2>Возвращенные книги</h2>
            <br />
            <div id="messageBox"></div>

            <table class="table table-striped">
                <thead>
                    <tr>
                        <th class="text-center">Название</th>
                        <th class="text-center">Автор</th>
                        <th class="text-center">Жанр</th>
                        <th class="text-center">Дата создания</th>
                        <th class="text-center">Количество</th>
                        <th class="text-center" colspan="2">Действия</th>
                    </tr>
                </thead>
                <tbody>
                    @foreach (var book in Model)
                    {
                        <tr id="@book.Id">
                            <td>@book.Title</td>
                            <td>@book.Author</td>
                            <td>@book.Genre.Title</td>
                            <td>@book.DateCreating.Year</td>
                            <td>@book.Count</td>
                            <td>
                                <form asp-action="ConfirmReturnBook" asp-controller="Store" class="float-left"
                                      data-ajax="true" data-ajax-method="POST"
                                      data-ajax-success="onSuccessConfirmBook"
                                      data-ajax-failure="onFailedConfirmBook">
                                    <input type="hidden" name="bookId" value="@book.Id" />
                                    <input type="hidden" name="countReturnBooks" value="@book.Count" />
                                    <button type="submit" class="btn btn-success">Принять</button>
                                </form>
                            </td>
                            <td>
                                <form asp-action="CancelReturnBook" asp-controller="Store" class="float-left"
                                      data-ajax="true" data-ajax-method="POST"
                                      data-ajax-success="onSuccessCancelBook"
                                      data-ajax-failure="onFailedCancelBook">
                                    <input type="hidden" name="bookId" value="@book.Id" />
                                    <button type="submit" class="btn btn-danger">Вернуть</button>
                                </form>
                            </td>
                        </tr>
                    }
                </tbody>
            </table>
        </div>
    </div>
</div>

@section Footer{
    <script src="~/lib/jquery-ajax-unobtrusive/jquery.unobtrusive-ajax.min.js"></script>
    <script src="~/js/BookKeeperBooksAJAX.js"></script>
}